/* English translation of bank/06_exc.js (module 6: timing exceptions) */
XT.bank.i18n('en', {
  modules: {
    exc: {
      title: '6. Timing exceptions: multicycle and false paths',
      about: 'set_multicycle_path (-setup/-hold, -start/-end), functional false paths, reset synchronizer and recovery/removal checks, exception priority',
    },
  },
  questions: {
    'exc.mcp_ce': {
      title: 'Multiplier with a clock enable: multicycle path',
      langNote: '`set_multicycle_path` and its defaults (`-end` for setup, `-start` for hold) are the same in Vivado and PrimeTime.',
      tags: ['set_multicycle_path', '-setup', '-hold', 'clock enable'],
      text: `
        A sample scaling block is clocked by \`clk\` at **200 MHz** (period 5 ns). The operands from the registers \`a_reg[7:0]\` and \`b_reg[7:0]\` feed a combinational 8 × 8-bit multiplier, and the product is written to the register \`prod_reg[15:0]\`.

        New samples arrive at half the clock rate, so all three registers are loaded only when the enable signal \`ce\` is active (CE inputs). It is generated by a divider counter inside the source block \`u_src\`: \`ce = 1\` in every second clock cycle. The operands loaded by edge *k* do not change until edge *k* + 2, and it is on that edge that the product is written to \`prod_reg\`. Without pipeline registers the multiplier does not fit into 5 ns, but it fits into 10 ns.

        **Task.** Allow two clock cycles for setup on the paths through the multiplier (from the operand registers to the product register), and keep the hold check correct. All other paths in the design, including the enable signal paths, must remain single-cycle.
      `,
      strings: {
        'источник отсчётов': 'sample source',
        'выход умножителя': 'multiplier output',
        'захват по умолчанию': 'default capture',
        'захват: -setup 2': 'capture: -setup 2',
        'задержка умножителя': 'multiplier delay',
        'требование к предустановке 10 нс': 'setup requirement 10 ns',
        'только -setup 2': '-setup 2 only',
        '-setup 2 и -hold 1': '-setup 2 and -hold 1',
        'запуск A1': 'launch A1',
        'удержание без -hold': 'hold without -hold',
        'захват A1·B1': 'capture A1·B1',
        'предустановка: 10 нс': 'setup: 10 ns',
        'удержание: 5 нс': 'hold: 5 ns',
        'удержание: 0 нс – проверка на фронте запуска': 'hold: 0 ns – check on the launch edge',
      },
      figures: [
        {
          title: 'Setup: the product is captured by the second edge',
          caption: 'The operands loaded by the edge at 0 ns remain unchanged until the edge at 10 ns. At the intermediate edge at 5 ns, ce = 0 and prod_reg keeps its previous value: an incomplete product is not captured.',
        },
        {
          title: 'Hold: where the check moves',
          caption: 'The hold check is performed on the edge preceding the capture edge. After -setup 2 this is the edge at 5 ns: the path through the multiplier would have to be longer than 5 ns, which is impossible. The -hold 1 command moves the check back to the launch edge (requirement 0 ns).',
        },
      ],
      hints: [
        'How many periods pass from the edge that loaded the operands to the edge that writes the product? That is the `-setup` multiplier.',
        'After `set_multicycle_path N -setup`, the hold check moves together with the capture edge. A second command, `set_multicycle_path N-1 -hold` with the same `-from` and `-to`, moves it back to the original edge.',
        'Scope: `-from [get_cells {a_reg[*] b_reg[*]}] -to [get_cells {prod_reg[*]}]`. A constraint with only `-to [get_cells {prod_reg[*]}]` is too broad: it also covers the enable path `u_src → prod_reg/CE`.',
      ],
      explain: `
        \`\`\`
        set_multicycle_path 2 -setup -from [get_cells {a_reg[*] b_reg[*]}] -to [get_cells {prod_reg[*]}]
        set_multicycle_path 1 -hold  -from [get_cells {a_reg[*] b_reg[*]}] -to [get_cells {prod_reg[*]}]
        \`\`\`
        - **Setup.** By default, data launched by the edge at 0 ns is captured by the next edge: requirement 5 ns. The \`-setup 2\` command moves the capture to the second edge after launch: requirement 2 · 5 = 10 ns. The multiplier counts periods of the capture clock (\`-end\` is the default); with a single clock it makes no difference.
        - **Hold.** The hold check is performed on the edge preceding the capture edge. After \`-setup 2\` this is the edge at 5 ns, and the hold requirement becomes 5 ns: even the shortest path through the multiplier must be longer than 5 ns. Vivado will try to "fix" such a violation with routing delays and degrade setup. The \`-hold 1\` command moves the check back to the launch edge: requirement 0 ns, as for an ordinary single-cycle path.
        - **Why this is valid.** The operands do not change for two clock cycles, and at the intermediate edge at 5 ns \`ce = 0\`, so \`prod_reg\` keeps its previous value. A multicycle path is acceptable only if the design logic guarantees it (here, the enable signal); otherwise the exception hides a real error.
        - **Scope.** The \`ce\` signal changes every cycle, so the \`u_src → …/CE\` paths must remain single-cycle. A constraint \`-to [get_cells {prod_reg[*]}]\` without \`-from\` covers all data inputs of the register, including CE: the requirement for the \`u_src → prod_reg/CE\` path would grow to 10 ns, and a timing error on the enable path would go unnoticed. An equivalent narrow form is \`-to [get_pins {prod_reg[*]/D}]\`: only the paths from the operand registers reach the D pins.

        Common mistakes:
        - no \`-hold\`: the hold requirement is 5 ns, which causes false violations and unnecessary routing delays;
        - \`-hold 2\`: the check moves to the edge at −5 ns (requirement −5 ns); it is always met and no longer protects against real violations, for example due to clock skew;
        - an exception between clocks (\`-from [get_clocks clk] -to [get_clocks clk]\`): all paths in the design become two-cycle paths.

        Check in Vivado: \`report_timing -from [get_cells {a_reg[0]}] -to [get_cells {prod_reg[15]}] -delay_type min_max\` shows a Requirement of 10 ns for setup and 0 ns for hold; \`report_exceptions\` shows how many paths each exception covers. In ConstraintLab the same is visible on the "Path analysis" tab.
      `,
      refs: 'UG903, section "Multicycle Paths"; Reference: "Correct multicycle path constraints"',
    },

    // -------------------------------------------------------------------------
    'exc.slow_fast': {
      title: 'Slow to fast domain: multicycle path with -end',
      langNote: 'The `-start`/`-end` options and the N and N−1 rule are the same in XDC and SDC; in an ASIC, the MMCM clocks would have to be defined manually.',
      tags: ['set_multicycle_path', '-end', 'related clocks', 'MMCM'],
      text: `
        The Clocking Wizard IP (\`u_clk\`) generates two clocks from the **100 MHz** signal on the \`sys_clk\` input: **50 MHz** (\`clk50\`) and **200 MHz** (\`clk200\`). Both come from the same MMCM, so they are related: the \`clk50\` rising edges coincide with every fourth \`clk200\` rising edge. Vivado derives these clocks automatically.

        An adaptation block in the \`clk50\` domain updates the coefficient \`coef_reg[7:0]\` on every edge of its clock. The filter datapath in the \`clk200\` domain copies the coefficient into the register \`coef_q_reg[7:0]\` when the enable signal \`ld\` from the phase counter \`u_ph\` is active: \`ld = 1\` only in the \`clk200\` cycle that ends with the edge coinciding with a \`clk50\` edge. Therefore, data launched by a \`clk50\` edge is stable for 4 \`clk200\` periods and is captured by the 4th \`clk200\` edge after launch.

        **Task.** Constrain the \`coef_reg → coef_q_reg\` transfer as a multicycle path: capture on the 4th \`clk200\` edge after launch, with the hold check on the original edge (requirement 0 ns).
      `,
      strings: {
        'CLKOUT0: 50 МГц': 'CLKOUT0: 50 MHz',
        'CLKOUT1: 200 МГц': 'CLKOUT1: 200 MHz',
        'адаптация': 'adaptation',
        'фазовый счётчик': 'phase counter',
        'предустановка': 'setup',
        'удержание': 'hold',
        'захват по умолчанию': 'default capture',
        'удержание без -hold': 'hold without -hold',
        'захват: -setup 4 -end': 'capture: -setup 4 -end',
        'по умолчанию 5 нс': 'default 5 ns',
        '-setup 4 -end: 20 нс': '-setup 4 -end: 20 ns',
        'только -setup: 15 нс': '-setup only: 15 ns',
      },
      figures: [
        {
          title: 'Launch on clk50, capture on the 4th clk200 edge',
          caption: 'Without an exception, capture happens on the nearest clk200 edge (5 ns). -setup 4 -end moves it by 3 clk200 periods, to 20 ns. The hold check follows it (to 15 ns); -hold 3 -end moves it back by 3 clk200 periods, to the edge at 0 ns.',
        },
      ],
      hints: [
        'For `-setup`, the multiplier counts periods of the capture clock by default (`-end`); here that is `clk200`. On which `clk200` edge does the capture happen?',
        'The hold check must be moved back by 3 periods of the **fast** clock. But for `-hold` the default is `-start`, that is, periods of the launch clock (`clk50`, 20 ns).',
        '`set_multicycle_path 4 -setup -end …` and `set_multicycle_path 3 -hold -end …` with the same `-from [get_cells {coef_reg[*]}] -to [get_cells {coef_q_reg[*]}]`.',
      ],
      explain: `
        \`\`\`
        set_multicycle_path 4 -setup -end -from [get_cells {coef_reg[*]}] -to [get_cells {coef_q_reg[*]}]
        set_multicycle_path 3 -hold  -end -from [get_cells {coef_reg[*]}] -to [get_cells {coef_q_reg[*]}]
        \`\`\`
        **Without exceptions.** For the 50 → 200 MHz pair, Vivado selects the nearest capture edge after launch: launch at 0 ns, capture at 5 ns, which gives a setup requirement of 5 ns and a hold requirement of 0 ns. This is stricter than necessary: by protocol, the data is captured at 20 ns.

        **Setup.** \`-setup 4 -end\` moves the capture edge forward by 3 \`clk200\` periods: 5 + 3 · 5 = 20 ns. For -setup, \`-end\` is the default, but writing it explicitly makes the intent obvious.

        **Hold.** The hold check follows the capture: after the shift it is performed on the \`clk200\` edge preceding the capture, that is, at 15 ns, which gives a requirement of 15 ns. \`-hold 3 -end\` moves it back by 3 periods of the **capture clock**: 15 − 3 · 5 = 0 ns.

        **The main trap: -end on -hold.** For -hold the default is \`-start\` (periods of the launch clock). The command \`set_multicycle_path 3 -hold\` without \`-end\` moves the check by 3 · 20 = 60 ns: the requirement becomes 15 − 60 = −45 ns, and the hold check becomes meaningless.

        | Constraints | Setup | Hold |
        |---|---|---|
        | no exceptions | 5 ns | 0 ns |
        | \`4 -setup -end\` only | 20 ns | 15 ns |
        | \`4 -setup -end\` and \`3 -hold -end\` | 20 ns | 0 ns – correct |
        | \`4 -setup -end\` and \`3 -hold\` (no -end) | 20 ns | −45 ns |
        | \`4 -setup -start\` and \`3 -hold -start\` | 65 ns | 0 ns |

        Rule: for a transfer from a slow clock to a fast one, the multipliers are counted in periods of the fast capture clock, and **both** commands are written with \`-end\`.

        Here there are no other paths between the domains, so \`-from [get_clocks clk50] -to [get_clocks clk200]\` is equivalent. In a real design, a targeted constraint on cells is safer: an exception between clocks silently relaxes any new transfers between these domains as well.

        Check in Vivado: \`report_timing -from [get_cells {coef_reg[0]}] -to [get_cells {coef_q_reg[0]}] -delay_type min_max\` shows a Requirement of 20 ns for setup and 0 ns for hold. In ConstraintLab, clicking a row on the "Path analysis" tab draws a diagram of the launch and capture edges.
      `,
      refs: 'UG903, section "Multicycle Paths", example for clocks with different frequencies; Reference: "Correct multicycle path constraints"',
    },

    // -------------------------------------------------------------------------
    'exc.fast_slow': {
      title: 'Fast to slow domain: multicycle path with -start',
      langNote: 'The `-start`/`-end` options and the N and N−1 rule are the same in XDC and SDC.',
      tags: ['set_multicycle_path', '-start', 'related clocks', 'MMCM'],
      text: `
        The same MMCM: \`clk200\` (200 MHz) and \`clk50\` (50 MHz); the \`clk50\` rising edges coincide with every fourth \`clk200\` rising edge.

        An accumulator in the \`clk200\` domain sums samples and updates the result register \`sum_reg[7:0]\` only when the enable signal \`ld\` from the phase counter \`u_ph\` is active: once every four cycles, on the edge that coincides with a \`clk50\` edge. A block in the \`clk50\` domain copies the result into the register \`sum_q_reg[7:0]\` on each of its edges. The value launched by the edge at 0 ns stays unchanged until 20 ns and is captured by the \`clk50\` edge at 20 ns.

        **Task.** Constrain the \`sum_reg → sum_q_reg\` transfer as a multicycle path: setup gets a full \`clk50\` period (4 \`clk200\` periods), and the hold check must stay on the original edge (requirement 0 ns).
      `,
      strings: {
        'CLKOUT0: 50 МГц': 'CLKOUT0: 50 MHz',
        'CLKOUT1: 200 МГц': 'CLKOUT1: 200 MHz',
        'накопитель': 'accumulator',
        'фазовый счётчик': 'phase counter',
        'предустановка': 'setup',
        'удержание': 'hold',
        'запуск: -setup 4 -start': 'launch: -setup 4 -start',
        'запуск для удержания без -hold': 'hold launch without -hold',
        'запуск по умолчанию': 'default launch',
        'по умолчанию 5 нс': 'default 5 ns',
        '-setup 4 -start: 20 нс': '-setup 4 -start: 20 ns',
        'только -setup: 15 нс': '-setup only: 15 ns',
      },
      figures: [
        {
          title: 'Launch on clk200 once every 4 cycles, capture on clk50',
          caption: 'By default Vivado takes the last clk200 edge before the capture (15 ns). -setup 4 -start moves the launch edge back by 3 clk200 periods, to 0 ns. After that, the hold check compares the capture at 20 ns with the next launch edge (5 ns); -hold 3 -start moves that edge to 20 ns, which gives a requirement of 0 ns.',
        },
      ],
      hints: [
        'Here the slow clock is the capture clock. You need to move the **launch** edge back and count the multiplier in `clk200` periods. Which option selects the launch clock?',
        'After `-setup 4 -start` the hold check moves as well. Move it back by 3 periods of the launch clock: `-hold 3 -start` (for -hold, -start is the default).',
        '`set_multicycle_path 4 -setup -start …` and `set_multicycle_path 3 -hold -start …` with the same `-from [get_cells {sum_reg[*]}] -to [get_cells {sum_q_reg[*]}]`.',
      ],
      explain: `
        \`\`\`
        set_multicycle_path 4 -setup -start -from [get_cells {sum_reg[*]}] -to [get_cells {sum_q_reg[*]}]
        set_multicycle_path 3 -hold  -start -from [get_cells {sum_reg[*]}] -to [get_cells {sum_q_reg[*]}]
        \`\`\`
        **Without exceptions.** For the 200 → 50 MHz pair, Vivado selects the last launch edge before the capture: launch at 15 ns, capture at 20 ns, which gives a setup requirement of 5 ns and a hold requirement of 0 ns.

        **Setup.** \`-setup 4 -start\` moves the launch edge back by 3 \`clk200\` periods: 15 − 3 · 5 = 0 ns, requirement 20 − 0 = 20 ns. Without \`-start\` (the default for -setup is \`-end\`), the shift would be counted in \`clk50\` periods: capture at 20 + 3 · 20 = 80 ns, requirement 65 ns; the path would get 45 ns more than it actually has, and a real violation would be hidden.

        **Hold.** After the shift, the hold check compares the capture at 20 ns with the *next* launch edge, at 5 ns: requirement 15 ns. \`-hold 3 -start\` moves the launch edge of this check forward by 3 \`clk200\` periods, to 20 ns: requirement 0 ns. For -hold, \`-start\` is the default, but writing it explicitly is clearer.

        | Constraints | Setup | Hold |
        |---|---|---|
        | no exceptions | 5 ns | 0 ns |
        | \`4 -setup -start\` only | 20 ns | 15 ns |
        | \`4 -setup -start\` and \`3 -hold -start\` | 20 ns | 0 ns – correct |
        | \`4 -setup -end\` and \`3 -hold -end\` | 65 ns | 0 ns |

        **Validity condition.** The source must hold the data stable for 4 \`clk200\` cycles (the \`ld\` signal ensures this) and update it on the edge that coincides with a \`clk50\` edge. If \`sum_reg\` changed every cycle, the multicycle path would hide a real transfer error: it would be an ordinary path with a 5 ns requirement.

        Rule for related clocks: slow to fast uses \`-end\`, fast to slow uses \`-start\`; the hold multiplier is one less than the setup multiplier and is written with the same option.

        Check in Vivado: \`report_timing -from [get_cells {sum_reg[0]}] -to [get_cells {sum_q_reg[0]}] -delay_type min_max\` shows a Requirement of 20 ns for setup and 0 ns for hold.
      `,
      refs: 'UG903, section "Multicycle Paths"; Reference: "Correct multicycle path constraints"',
    },

    // -------------------------------------------------------------------------
    'exc.static_cfg': {
      title: 'Configuration registers: functional false path',
      langNote: 'A targeted `set_false_path` is the same in XDC and SDC.',
      tags: ['set_false_path', 'quasi-static signals', 'related clocks'],
      text: `
        A processor (domain \`clk_cpu\`, **100 MHz**) writes a gain coefficient for the processing datapath (domain \`clk_dsp\`, **150 MHz**) into the configuration registers \`cfg_reg[15:0]\`. Both clocks come from the same MMCM, so Vivado analyzes the paths between the domains as synchronous.

        By the operating protocol, the coefficient changes only while the datapath is stopped: the software clears the run enable, writes \`cfg_reg\`, and only then starts the datapath with a command that travels along the \`start_reg → run_reg\` path. Hundreds of clock cycles pass between writing the coefficient and its first use. The start command itself is an ordinary synchronous transfer between the domains.

        Currently, the timing report shows a 3.333 ns setup requirement and violations on the \`cfg_reg → res_reg\` paths.

        **Task.** Exclude the paths from the configuration registers to the processing datapath from timing analysis. All other paths, including other paths between \`clk_cpu\` and \`clk_dsp\`, must still be analyzed.
      `,
      strings: {
        'CLKOUT0: 100 МГц': 'CLKOUT0: 100 MHz',
        'CLKOUT1: 150 МГц': 'CLKOUT1: 150 MHz',
        'шина процессора': 'CPU bus',
        'приём отсчётов': 'sample input',
        'усиление': 'gain',
        'требование': 'requirement',
        '6,667 нс': '6.667 ns',
        '3,333 нс': '3.333 ns',
      },
      figures: [
        {
          title: 'Related 100 and 150 MHz clocks: the worst edge pair',
          caption: 'The common period of the 100 and 150 MHz clocks is 20 ns. The worst pair is launch at 10 ns and capture at 13.333 ns: a setup requirement of 3.333 ns. For the start command this is a real requirement; for the quasi-static configuration registers it is not.',
        },
      ],
      hints: [
        'The clocks are related (one MMCM), so `set_clock_groups -asynchronous` is inappropriate here. The exception must cover only the paths that start at `cfg_reg`.',
        '`set_false_path -from [get_cells {cfg_reg[*]}]` covers all paths that start at the configuration registers. You can add `-to` for clarity.',
      ],
      explain: `
        \`\`\`
        set_false_path -from [get_cells {cfg_reg[*]}]
        \`\`\`
        **Where 3.333 ns comes from.** The common period of the 100 and 150 MHz clocks is 20 ns. Within it, the \`clk_cpu\` rising edges are at 0 and 10 ns, and the \`clk_dsp\` rising edges at 0, 6.667 and 13.333 ns. For the launch at 10 ns, the nearest capture is at 13.333 ns: a setup requirement of 3.333 ns. Vivado must check every synchronous path against the worst edge pair.

        **Why the path is functionally false.** The \`cfg_reg\` value changes only while the datapath is stopped and is used hundreds of cycles later, so it does not matter on which \`clk_dsp\` edge the new value reaches the datapath. This is a property of the **protocol**, not of the clocks: the clocks are synchronous, and other paths between them must be analyzed. Such signals are called quasi-static.

        **What is wrong with global exceptions.** \`set_clock_groups -asynchronous\` or \`set_false_path -from [get_clocks clk_cpu] -to [get_clocks clk_dsp]\` would also exclude the start command \`start_reg → run_reg\`. That is a real synchronous transfer: without analysis it may not fit into 3.333 ns, and the datapath would start only intermittently. Besides, declaring clocks from the same MMCM asynchronous is methodologically wrong: \`report_clock_interaction\` would no longer show the real relationship between the domains.

        **Do not cover too much.** \`set_false_path -to [get_cells {res_reg[*]}]\` would also exclude the paths from the sample receiver \`u_adc\` to \`res_reg\` inside the \`clk_dsp\` domain, leaving the main processing datapath unanalyzed.

        **Alternative: a delay constraint.** If it matters when the new value is guaranteed to reach the datapath (for example, the datapath is not stopped during the write), specify a maximum delay instead of a false path: \`set_max_delay 20.000 -from [get_cells {cfg_reg[*]}] -to [get_cells {res_reg[*]}]\`. The path is then constrained to a reasonable value (here two \`clk_cpu\` periods) rather than 3.333 ns. The choice depends on the protocol; in this task the protocol guarantees that the datapath is stopped, so a false path is sufficient.

        Check in Vivado: \`report_clock_interaction\` shows the status *Partial False Path* for the \`clk_cpu → clk_dsp\` pair (some paths are excluded, the rest are analyzed); \`report_exceptions\` shows that the exception covers 16 paths; \`report_timing -from [get_cells start_reg]\` shows the start path still with a 3.333 ns requirement.
      `,
      refs: 'UG903, section "False Paths"; UG949, section on quasi-static signals; Reference: "Clock domain crossing: what to constrain"',
    },

    // -------------------------------------------------------------------------
    'exc.reset_sync': {
      title: 'Reset synchronizer: false path from a push button, ASYNC_REG',
      langNote: '`set_false_path` and the recovery and removal checks are common to XDC and SDC; the `ASYNC_REG` property exists only in Vivado.',
      tags: ['set_false_path', 'ASYNC_REG', 'reset', 'recovery/removal'],
      text: `
        A reset push button is connected to the \`rst_n\` pin (active low); the moments when it is pressed and released are in no way related to the clocks. Inside the FPGA the signal passes through an input buffer and an inverter and drives the asynchronous preset inputs PRE of a reset synchronizer built from two FDPE flip-flops: \`rst_sync_reg[0]\` and \`rst_sync_reg[1]\`. The D input of the first flip-flop is tied to logic 0, and the D input of the second is driven by the output of the first.

        The circuit **asserts** the reset asynchronously (a press immediately sets both flip-flops to 1) and **deasserts** it synchronously, two \`clk\` edges after the button is released. The \`rst_sync_reg[1]\` output drives the asynchronous clear inputs CLR of the working registers \`cnt_reg[7:0]\` (FDCE).

        The \`clk\` clock (100 MHz) is already defined. No input delay is specified for \`rst_n\`, and \`check_timing\` reports this port as *no_input_delay*.

        **Task.** Exclude the paths from the \`rst_n\` port from the analysis and mark both synchronizer flip-flops with the \`ASYNC_REG\` property. The paths from the synchronizer to the working registers must remain analyzed.
      `,
      strings: {
        'НЕ': 'NOT',
        'rst_n (кнопка)': 'rst_n (button)',
        'нажатие': 'press',
        'отпускание': 'release',
        'запуск снятия сброса': 'deassertion launch',
        'захват: восстановление': 'capture: recovery',
        '10 нс': '10 ns',
      },
      figures: [
        {
          title: 'Asynchronous reset assertion, synchronous deassertion',
          caption: 'A press immediately sets both flip-flops to 1 (asynchronously), and the working registers are reset. The release is random with respect to clk: the first flip-flop may become metastable (hatched), and the second gives it a full period to resolve. The reset is deasserted by the edge at 40 ns, and the rst_sync_reg[1] → CLR path is checked for recovery (before the edge at 50 ns) and removal (relative to the edge at 40 ns).',
        },
      ],
      hints: [
        'It makes no sense to check the paths from the button against `clk`: the moment of a press is random, which is exactly why the synchronizer is there. You need a false path whose startpoint is the port.',
        'The property is set with `set_property ASYNC_REG TRUE [get_cells …]`, for both synchronizer flip-flops.',
        'Do not exclude the `rst_sync_reg[1] → cnt_reg/CLR` paths: these are the recovery and removal checks, and they are mandatory.',
      ],
      explain: `
        \`\`\`
        set_false_path -from [get_ports rst_n]
        set_property ASYNC_REG TRUE [get_cells {rst_sync_reg[*]}]
        \`\`\`
        **The path from the button.** Pressing and releasing are not related to \`clk\`, so checks on the \`rst_n → PRE\` path are meaningless: the synchronizer is designed precisely for an arbitrary moment of input change. Without an input delay, Vivado does not analyze this path anyway, but the port stays in the \`check_timing\` report (*no_input_delay*), and if someone later adds a blanket constraint such as \`set_input_delay … [all_inputs]\`, the path will start being analyzed against \`clk\` with a meaningless result. An explicit false path records the intent.

        **ASYNC_REG.** The button release can fall into the recovery window of the first flip-flop, and \`rst_sync_reg[0]\` then becomes metastable. The second flip-flop gives it a full period to resolve. The \`ASYNC_REG\` property tells Vivado that the flip-flops form a synchronizer: they are placed close together (in one slice), not merged into an SRL shift register, not replicated during optimization, and taken into account in the mean time between failures (MTBF) estimate.

        **Recovery and removal.** The \`rst_sync_reg[1]\` output changes synchronously with \`clk\`, while the asynchronous CLR input of a flip-flop has its own timing requirements: the reset must be deasserted no later than the recovery time before the clock edge and no earlier than the removal time after the edge. Otherwise some registers leave reset one cycle later than the others, and a counter or state machine starts in an illegal state. Vivado analyzes the \`rst_sync_reg[1] → cnt_reg/CLR\` path like an ordinary synchronous one: a recovery requirement of 10 ns and a removal requirement of 0 ns. It must not be excluded: the reset is deasserted synchronously precisely for the sake of this check.

        Common mistakes:
        - \`set_false_path -to [get_pins -hier -filter {REF_PIN_NAME == CLR}]\` or \`-from [get_cells {rst_sync_reg[1]}]\` disables the recovery and removal checks. A high-fanout reset net can easily have a delay of several nanoseconds, and the violation would go unnoticed;
        - \`set_false_path -to [get_cells {rst_sync_reg[*]}]\` excludes, together with the paths from the button, the \`rst_sync_reg[0] → rst_sync_reg[1]\` path. This is a synchronous path inside the synchronizer: the shorter it is, the more time is left for metastability to resolve;
        - no \`ASYNC_REG\`: synthesis may pack the flip-flops into an SRL or scatter them across the die.

        Check in Vivado: \`report_timing -to [get_pins {cnt_reg[0]/CLR}] -delay_type min_max\` shows the recovery and removal checks; \`report_exceptions\` shows the false path from \`rst_n\` (the port may remain in the *no_input_delay* list of the \`check_timing\` report: that check looks at whether the port has a delay, not at exceptions); \`report_property [get_cells {rst_sync_reg[0]}]\` shows the ASYNC_REG value.
      `,
      refs: 'UG903, section "False Paths"; UG949, recommendations on resets and synchronizers; UG912, ASYNC_REG property',
    },

    // -------------------------------------------------------------------------
    'exc.priority': {
      title: 'Three exceptions on one path: what will Vivado check?',
      langNote: 'The order "false path → delay constraint → multicycle path" is the same in PrimeTime.',
      tags: ['exception priority', 'set_max_delay', 'set_false_path -hold'],
      text: `
        In a design with a **100 MHz** clock \`clk\` (period 10 ns), three exceptions from different constraint files apply to the \`ctl_reg → dout_reg\` path at once:

        \`\`\`
        set_multicycle_path 2 -setup -from [get_cells ctl_reg] -to [get_cells dout_reg]
        set_max_delay 4.000 -from [get_cells ctl_reg] -to [get_cells dout_reg]
        set_false_path -hold -from [get_cells ctl_reg] -to [get_cells dout_reg]
        \`\`\`

        **Task.** Determine which checks Vivado performs on this path and with what requirement.
      `,
      strings: {
        'логика': 'logic',
        'по умолчанию': 'default',
        'следующий фронт': 'next edge',
        'второй фронт': 'second edge',
        '4 нс': '4 ns',
        '10 нс': '10 ns',
        '20 нс': '20 ns',
      },
      figures: [
        {
          title: 'Requirements proposed by the three exceptions',
          caption: 'Each exception on its own would produce its own setup requirement. Which one takes effect is determined by exception priority, not by the order of the commands or by how strict the value is.',
        },
      ],
      hints: [
        'Priority is determined by the exception type: clock groups → false path → `set_max_delay`/`set_min_delay` → multicycle path.',
        'The `-hold` option of `set_false_path` means that the exception applies only to the hold check. For setup, find the next exception in order of precedence.',
      ],
      options: [
        {
          text: 'Setup with a 4 ns requirement (from `set_max_delay`); hold is not checked.',
          why: 'Correct. A delay constraint has higher priority than a multicycle path, so 4 ns applies to setup. A false path with the -hold option disables only the hold check.',
        },
        {
          text: 'Setup with a 20 ns requirement (multicycle path); hold is not checked.',
          why: 'The multicycle path is the exception with the lowest priority: set_max_delay on the same path overrides it regardless of the order of the commands in the file.',
        },
        {
          text: 'The path is not analyzed at all: the false path has the highest priority of the three.',
          why: 'The priority of a false path applies only to the check it refers to. With the -hold option, hold is disabled and setup remains.',
        },
        {
          text: 'Setup 4 ns; hold with a 10 ns requirement, shifted by the multicycle path without -hold.',
          why: 'Hold is disabled by the -hold false path. Moreover, set_multicycle_path is completely overridden here by the set_max_delay constraint and does not shift any checks.',
        },
        {
          text: 'The strictest value applies: setup 4 ns, hold 0 ns by default.',
          why: 'Exceptions are not compared by strictness: the choice is determined by the exception type. The match for setup is a coincidence here: with set_max_delay 25, 25 ns would apply, even though the multicycle path gives 20 ns. And hold is disabled by the false path.',
        },
      ],
      explain: `
        Exception priority in Vivado (and in SDC):
        1. \`set_clock_groups\` (highest);
        2. \`set_false_path\`;
        3. \`set_max_delay\` and \`set_min_delay\`;
        4. \`set_multicycle_path\` (lowest).

        Priority is applied **separately** to the setup check and to the hold check:
        - **setup:** there is no false path for it (that one is specified with \`-hold\`), and \`set_max_delay 4\` takes precedence over the multicycle path, so the requirement is 4 ns;
        - **hold:** \`set_false_path -hold\`, so the check is not performed.

        The multicycle path is completely overridden and has no effect. The order of the commands in the file does not affect priority **between types**. Within one type, the more specific exception wins: one specified on cells and pins beats one specified on clocks, and \`-from\` beats \`-to\`; with equal specificity, the last one applies.

        Note: \`set_max_delay\` without \`-datapath_only\` still accounts for clock skew, and the 4 ns requirement here is **stricter** than the default one (10 ns); such a constraint is sometimes used to reserve time on a path. If, however, the designer counted on the multicycle path, they will get unexpected violations: mixing exceptions of different types on one path is a source of errors.

        Check: \`report_exceptions\` shows which exceptions are in effect and which are overridden (in ConstraintLab: "overridden by a higher-priority exception"); in Vivado, \`report_exceptions -ignored\` lists completely overridden exceptions. \`report_timing -from [get_cells ctl_reg] -to [get_cells dout_reg] -delay_type min_max\` shows the 4 ns setup requirement and no hold check.
      `,
      refs: 'UG903, section "Exceptions Priority"; Reference: "Timing exception priority"',
    },

    // -------------------------------------------------------------------------
    'exc.mcp_numbers': {
      title: 'Calculation: multicycle path with and without -hold',
      langNote: 'Multicycle path requirements are calculated the same way in Vivado and PrimeTime.',
      tags: ['set_multicycle_path', 'calculation'],
      text: `
        The registers \`x_reg\` and \`y_reg\` are clocked by the same clock with a period of **T = 5 ns**; the source updates the data once every three cycles, and the receiver captures it using an enable signal. The designer constrained the path with the command

        \`\`\`
        set_multicycle_path 3 -setup -from [get_cells x_reg] -to [get_cells y_reg]
        \`\`\`

        and forgot about hold. Later, a second command was added:

        \`\`\`
        set_multicycle_path 2 -hold -from [get_cells x_reg] -to [get_cells y_reg]
        \`\`\`

        The launch edge is at 0 ns; the clock is ideal.

        **Task.** Determine the requirements (edge relationships) in nanoseconds.
      `,
      strings: {
        'вычисление': 'computation',
        'фронт 1': 'edge 1',
        'фронт 2': 'edge 2',
        'фронт 3': 'edge 3',
        'фронт 4': 'edge 4',
      },
      figures: [
        {
          title: 'Source data stable for three cycles',
          caption: 'Count to which edge the -setup 3 command moves the capture, and on which edge the hold check is performed after that.',
        },
      ],
      fields: [
        { label: 'Setup requirement (`-setup 3` only)' },
        { label: 'Hold requirement (`-setup 3` only)' },
        { label: 'Hold requirement after adding `-hold 2`' },
      ],
      hints: [
        'By default, capture happens on the next edge (5 ns). `-setup N` moves it to the Nth edge after launch.',
        'The hold check is performed on the edge preceding the setup capture edge, and `-hold M` moves it back by another M periods.',
      ],
      explain: `
        **Setup.** The capture moves to the 3rd edge after launch: 3 · T = 15 ns.

        **Hold without -hold.** The hold check is performed on the capture edge preceding the setup edge: 15 − 5 = 10 ns, that is, (N − 1) · T. A 10 ns requirement means that the path must be **longer** than 10 ns: a violation is almost inevitable, and Vivado's attempts to fix it with routing delays will ruin setup.

        **With -hold 2.** The check moves back by another 2 periods: 10 − 2 · 5 = 0 ns, as for an ordinary single-cycle path. Data launched by the next source edge must not corrupt the capture on that same edge.

        General formula for a single clock: setup N · T; hold (N − 1 − M) · T, where M is the \`-hold\` multiplier. The correct pair: M = N − 1.

        | Constraints | Setup | Hold |
        |---|---|---|
        | no exceptions | 5 ns | 0 ns |
        | \`3 -setup\` | 15 ns | 10 ns |
        | \`3 -setup\`, \`2 -hold\` | 15 ns | 0 ns |
        | \`3 -setup\`, \`3 -hold\` (one cycle too many) | 15 ns | −5 ns |

        You can verify the calculation in the console of any task with a single clock: \`report_timing -from … -to … -delay_type min_max\` shows the requirement for both checks.
      `,
      refs: 'UG903, section "Multicycle Paths"; Reference: "Correct multicycle path constraints"',
    },
  },
});
